version: "3.8"

services:

  api:
    image: api
    container_name: 'api'
    build: ./api
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mongodb://admin:admin@mongodb:27017
    volumes:
      - ./api:/usr/app
    depends_on:
      - mongodb

  creator:
    image: creator
    container_name: 'creator'
    build: ./creator
    restart: always
    environment:
      API_URL: http://api:3000/api
    volumes:
      - ./creator:/usr/app
    depends_on:
      - api

  web:
    image: web
    container_name: 'web'
    build: ./web
    restart: always
    environment:
      API_URL: http://api:3000/api
    ports:
      - 8081:3000
    volumes:
      - ./web:/usr/app
    depends_on:
      - api

  mongodb:
    container_name: 'mongodb'
    image: mongo:4.4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongodbexpress:
    container_name: 'mongodbexpress'
    image: mongo-express:0.54
    restart: always
    ports:
      - 8000:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongodb
